# -*- coding: utf-8 -*-
"""AdditiveCipher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b9HsbYyJRKqO2FHoxNlG77OXKuq2u-7R
"""

# Function to shift characters in the Turkish alphabet by a specified number
def shift_text(text, shift_amount):
    turkish_alphabet = "ABCÇDEFGĞHIİJKLKMNOPRSŞTUÜVYZ"
    shifted_text = []

    for char in text:
        if char in turkish_alphabet:
            # Find the index of the character in the Turkish alphabet
            idx = turkish_alphabet.index(char)
            # Shift the letter by the specified number of positions
            shifted_idx = (idx + shift_amount) % len(turkish_alphabet)
            shifted_text.append(turkish_alphabet[shifted_idx])
        else:
            # If the character is not in the alphabet, just append it as it is
            shifted_text.append(char)

    # Return the shifted text as a string
    return ''.join(shifted_text)

# Your input text
input_text = "DMSVKMKZNKÖIGMÜŞKJKGÜNHZJDSMKRÜJHTSMMAÇMSJÜJKŞSZLLSUİSÖACÜÇKÖÜJÜŞÜÇKNLKGHZNDÖHÖDNIGMÜVSÇSMAŞJÜJKSMKRÜKUÜJKKUÜJKHMDZJKGÜGSÖALMSJAİÜGGSÖKÖÜNIGMFGHZNSŞHÖDJÜŞÜÇKNLKGHZDŞPSLÜÖKÇKNKJÜSGÖAİSCÇSRAYKOJÜSGÖAİÜGJÜTKMJÜJKVIGMÜHMJDÇLSÖNHÖZSNIPEÜMKİKGÜJKTKŞKEIZFZFŞÖÜJÜŞÜÇNÜEIZJFTFŞFGÜZKŞJÜŞÜÇ"

# Set the shift amount (can be any number, like 1, 2, 29, etc.)
shift_amount = 29

# Call the function to shift the text
shifted_text = shift_text(input_text, shift_amount)

# Print the result
print(f"Original Text: {input_text}")
print(f"Shifted Text by {shift_amount} positions: {shifted_text}")